<?php

declare(strict_types=1);

return [
    'storage' => [
        'disk' => env('EXPORT_STORAGE_DISK', 'local'),
        'path' => env('EXPORT_STORAGE_PATH', 'exports'),
        'retention_days' => env('EXPORT_RETENTION_DAYS', 7),
    ],
    'chunk_size' => env('EXPORT_CHUNK_SIZE', 1000),
    'max_file_size' => env('EXPORT_MAX_FILE_SIZE', 50 * 1024 * 1024), // 50MB
    'file_ttl' => env('EXPORT_FILE_TTL', 7), // days
    'logo_path' => env('EXPORT_LOGO_PATH', 'assets/logo.png'),
    'footer_text' => env('EXPORT_FOOTER_TEXT', 'Generated by CRM System'),
];
