<?php

declare(strict_types=1);

namespace Tests\Unit\Services\Export;

use App\Config\ExportConfig;
use App\Services\Export\ExportService;
use App\Services\Export\Formatters\CsvFormatter;
use App\Services\Export\Formatters\PdfFormatter;
use App\Services\Export\Formatters\XlsxFormatter;
use Carbon\Carbon;
use Illuminate\Contracts\Filesystem\Filesystem;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Storage;
use Mockery;
use Psr\Log\LoggerInterface;
use Tests\TestCase;

class ExportServiceTest extends TestCase
{
    private ExportService $exportService;

    private CsvFormatter $csvFormatter;

    private XlsxFormatter $xlsxFormatter;

    private PdfFormatter $pdfFormatter;

    private LoggerInterface $logger;

    private Filesystem $storage;

    private ExportConfig $config;

    private Carbon $now;

    protected function setUp(): void
    {
        parent::setUp();

        $this->csvFormatter = Mockery::mock(CsvFormatter::class);
        $this->xlsxFormatter = Mockery::mock(XlsxFormatter::class);
        $this->pdfFormatter = Mockery::mock(PdfFormatter::class);
        $this->logger = Mockery::mock(LoggerInterface::class);
        $this->storage = Mockery::mock(Filesystem::class);
        $this->config = new ExportConfig(
            storagePath: 'exports',
            maxFileSize: 50 * 1024 * 1024,
            chunkSize: 1000,
            fileTtl: 7,
            logoPath: 'assets/logo.png',
            footerText: 'Generated by CRM System',
        );
        $this->now = Mockery::mock(Carbon::class);

        $this->exportService = new ExportService(
            $this->csvFormatter,
            $this->xlsxFormatter,
            $this->pdfFormatter,
            $this->logger,
            $this->storage
        );

        Storage::fake('local');
    }

    protected function tearDown(): void
    {
        Mockery::close();
        parent::tearDown();
    }

    public function test_export_to_csv_creates_file_and_returns_response(): void
    {
        $data = [
            ['name' => 'John Doe', 'email' => 'john@example.com'],
            ['name' => 'Jane Smith', 'email' => 'jane@example.com'],
        ];
        $filename = 'test_export';
        $headers = ['Name', 'Email'];
        $csvContent = "Name,Email\nJohn Doe,john@example.com\nJane Smith,jane@example.com\n";

        $this->csvFormatter
            ->expects('format')
            ->with($data, $headers)
            ->andReturn($csvContent);

        $this->logger
            ->expects('info')
            ->with('Starting CSV export', [
                'filename' => $filename,
                'record_count' => 2,
            ]);

        $this->storage
            ->expects('put')
            ->with('exports/test_export.csv', $csvContent);

        $this->storage
            ->expects('get')
            ->with('exports/test_export.csv')
            ->andReturn($csvContent);

        $this->logger
            ->expects('info')
            ->with('File stored successfully', [
                'path' => 'exports/test_export.csv',
                'size' => strlen($csvContent),
            ]);

        $response = $this->exportService->exportToCsv($data, $filename, $headers);

        $this->assertInstanceOf(Response::class, $response);
        $this->assertEquals('text/csv; charset=UTF-8', $response->headers->get('Content-Type'));
        $this->assertStringContainsString('attachment; filename="test_export.csv"', $response->headers->get('Content-Disposition'));
    }

    public function test_export_to_xlsx_creates_file_and_returns_response(): void
    {
        $data = [
            ['name' => 'John Doe', 'email' => 'john@example.com'],
        ];
        $filename = 'test_export';
        $headers = ['Name', 'Email'];
        $options = ['title' => 'Test Export'];
        $xlsxContent = 'mock xlsx content';

        $this->xlsxFormatter
            ->expects('format')
            ->with($data, $headers, $options)
            ->andReturn($xlsxContent);

        $this->logger
            ->expects('info')
            ->with('Starting XLSX export', [
                'filename' => $filename,
                'record_count' => 1,
            ]);

        $this->storage
            ->expects('put')
            ->with('exports/test_export.xlsx', $xlsxContent);

        $this->storage
            ->expects('get')
            ->with('exports/test_export.xlsx')
            ->andReturn($xlsxContent);

        $this->logger
            ->expects('info')
            ->with('File stored successfully', [
                'path' => 'exports/test_export.xlsx',
                'size' => strlen($xlsxContent),
            ]);

        $response = $this->exportService->exportToXlsx($data, $filename, $headers, $options);

        $this->assertInstanceOf(Response::class, $response);
        $this->assertEquals('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', $response->headers->get('Content-Type'));
        $this->assertStringContainsString('attachment; filename="test_export.xlsx"', $response->headers->get('Content-Disposition'));
    }

    public function test_export_to_pdf_creates_file_and_returns_response(): void
    {
        $data = [
            ['name' => 'John Doe', 'email' => 'john@example.com'],
        ];
        $filename = 'test_export';
        $headers = ['Name', 'Email'];
        $options = ['title' => 'Test Export'];
        $pdfContent = 'mock pdf content';

        $this->pdfFormatter
            ->expects('format')
            ->with($data, $headers, $options)
            ->andReturn($pdfContent);

        $this->logger
            ->expects('info')
            ->with('Starting PDF export', [
                'filename' => $filename,
                'record_count' => 1,
            ]);

        $this->storage
            ->expects('put')
            ->with('exports/test_export.pdf', $pdfContent);

        $this->storage
            ->expects('get')
            ->with('exports/test_export.pdf')
            ->andReturn($pdfContent);

        $this->logger
            ->expects('info')
            ->with('File stored successfully', [
                'path' => 'exports/test_export.pdf',
                'size' => strlen($pdfContent),
            ]);

        $response = $this->exportService->exportToPdf($data, $filename, $headers, $options);

        $this->assertInstanceOf(Response::class, $response);
        $this->assertEquals('application/pdf', $response->headers->get('Content-Type'));
        $this->assertStringContainsString('attachment; filename="test_export.pdf"', $response->headers->get('Content-Disposition'));
    }

    public function test_export_with_chunking_handles_large_datasets(): void
    {
        $dataProvider = function (int $offset, int $limit) {
            if ($offset === 0) {
                return [
                    ['name' => 'John Doe', 'email' => 'john@example.com'],
                    ['name' => 'Jane Smith', 'email' => 'jane@example.com'],
                ];
            }

            return [];
        };

        $filename = 'chunked_export';
        $format = 'csv';
        $headers = ['Name', 'Email'];
        $csvContent = "Name,Email\nJohn Doe,john@example.com\nJane Smith,jane@example.com\n";

        $this->csvFormatter
            ->expects('format')
            ->with([
                ['name' => 'John Doe', 'email' => 'john@example.com'],
                ['name' => 'Jane Smith', 'email' => 'jane@example.com'],
            ], $headers)
            ->andReturn($csvContent);

        $this->logger
            ->expects('info')
            ->with('Starting chunked export', [
                'filename' => $filename,
                'format' => $format,
            ]);

        $this->logger
            ->expects('info')
            ->with('Starting CSV export', [
                'filename' => $filename,
                'record_count' => 2,
            ]);

        $this->storage
            ->expects('put')
            ->with('exports/chunked_export.csv', $csvContent);

        $this->storage
            ->expects('get')
            ->with('exports/chunked_export.csv')
            ->andReturn($csvContent);

        $this->logger
            ->expects('info')
            ->with('File stored successfully', [
                'path' => 'exports/chunked_export.csv',
                'size' => strlen($csvContent),
            ]);

        $response = $this->exportService->exportWithChunking($dataProvider, $filename, $format, $headers);

        $this->assertInstanceOf(Response::class, $response);
    }

    public function test_export_with_chunking_throws_exception_for_unsupported_format(): void
    {
        $dataProvider = function (int $offset, int $limit) {
            return [];
        };

        $this->logger
            ->expects('info')
            ->with('Starting chunked export', [
                'filename' => 'test',
                'format' => 'invalid',
            ]);

        $this->expectException(\App\Exceptions\Export\ExportGenerationException::class);
        $this->expectExceptionMessage('Failed to generate invalid export: Unsupported format');

        $this->exportService->exportWithChunking($dataProvider, 'test', 'invalid', []);
    }

    public function test_cleanup_old_files_removes_old_files(): void
    {
        $this->storage
            ->expects('files')
            ->with('exports')
            ->andReturn(['exports/old_file.csv', 'exports/new_file.csv']);

        $this->storage
            ->expects('lastModified')
            ->with('exports/old_file.csv')
            ->andReturn(now()->subDays(10)->timestamp);

        $this->storage
            ->expects('lastModified')
            ->with('exports/new_file.csv')
            ->andReturn(now()->subDays(1)->timestamp);

        $this->storage
            ->expects('delete')
            ->with('exports/old_file.csv');

        $this->logger
            ->expects('info')
            ->with('Cleaned up old export files', Mockery::type('array'));

        $deletedCount = $this->exportService->cleanupOldFiles();

        $this->assertIsInt($deletedCount);
    }
}
