<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\Crm\ContactStatus;
use App\Enums\Crm\LeadLevel;
use App\Models\Contact;
use Illuminate\Database\Seeder;

class ContactSeeder extends Seeder
{
    public function run(): void
    {
        $contacts = [
            [
                'first_name' => 'John',
                'last_name' => 'Smith',
                'email' => 'john.smith@techcorp.com',
                'phone' => '+1-555-0101',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'website',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@globalmfg.com',
                'phone' => '+44-20-7946-0958',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'referral',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Brown',
                'email' => 'michael.brown@digitalmarketing.com',
                'phone' => '+1-555-0102',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'social_media',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Emma',
                'last_name' => 'Davis',
                'email' => 'emma.davis@healthcare.com',
                'phone' => '+44-20-7946-0959',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'email_campaign',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Wilson',
                'email' => 'david.wilson@financial.com',
                'phone' => '+81-3-1234-5678',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'cold_call',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Anderson',
                'email' => 'lisa.anderson@retailchain.com',
                'phone' => '+1-555-0103',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'trade_show',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Robert',
                'last_name' => 'Taylor',
                'email' => 'robert.taylor@energy.com',
                'phone' => '+44-20-7946-0960',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'partner',
                'status' => ContactStatus::DORMANT->value,
            ],
            [
                'first_name' => 'Jennifer',
                'last_name' => 'Martinez',
                'email' => 'jennifer.martinez@education.org',
                'phone' => '+1-555-0104',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'website',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Garcia',
                'email' => 'james.garcia@logistics.com',
                'phone' => '+81-3-1234-5679',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'referral',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Maria',
                'last_name' => 'Rodriguez',
                'email' => 'maria.rodriguez@consulting.com',
                'phone' => '+44-20-7946-0961',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'other',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'William',
                'last_name' => 'Lee',
                'email' => 'william.lee@techcorp.com',
                'phone' => '+1-555-0105',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'website',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Patricia',
                'last_name' => 'White',
                'email' => 'patricia.white@globalmfg.com',
                'phone' => '+44-20-7946-0962',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'referral',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Christopher',
                'last_name' => 'Harris',
                'email' => 'chris.harris@digitalmarketing.com',
                'phone' => '+1-555-0106',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'social_media',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Linda',
                'last_name' => 'Clark',
                'email' => 'linda.clark@healthcare.com',
                'phone' => '+44-20-7946-0963',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'email_campaign',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Daniel',
                'last_name' => 'Lewis',
                'email' => 'daniel.lewis@financial.com',
                'phone' => '+81-3-1234-5680',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'cold_call',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Barbara',
                'last_name' => 'Walker',
                'email' => 'barbara.walker@retailchain.com',
                'phone' => '+1-555-0107',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'trade_show',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Richard',
                'last_name' => 'Hall',
                'email' => 'richard.hall@energy.com',
                'phone' => '+44-20-7946-0964',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'partner',
                'status' => ContactStatus::DORMANT->value,
            ],
            [
                'first_name' => 'Susan',
                'last_name' => 'Allen',
                'email' => 'susan.allen@education.org',
                'phone' => '+1-555-0108',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'website',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Joseph',
                'last_name' => 'Young',
                'email' => 'joseph.young@logistics.com',
                'phone' => '+81-3-1234-5681',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'referral',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Jessica',
                'last_name' => 'King',
                'email' => 'jessica.king@consulting.com',
                'phone' => '+44-20-7946-0965',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'other',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Thomas',
                'last_name' => 'Wright',
                'email' => 'thomas.wright@techcorp.com',
                'phone' => '+1-555-0109',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'website',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Nancy',
                'last_name' => 'Lopez',
                'email' => 'nancy.lopez@globalmfg.com',
                'phone' => '+44-20-7946-0966',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'referral',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Charles',
                'last_name' => 'Hill',
                'email' => 'charles.hill@digitalmarketing.com',
                'phone' => '+1-555-0110',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'social_media',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Karen',
                'last_name' => 'Scott',
                'email' => 'karen.scott@healthcare.com',
                'phone' => '+44-20-7946-0967',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'email_campaign',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Mark',
                'last_name' => 'Green',
                'email' => 'mark.green@financial.com',
                'phone' => '+81-3-1234-5682',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'cold_call',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Betty',
                'last_name' => 'Adams',
                'email' => 'betty.adams@retailchain.com',
                'phone' => '+1-555-0111',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'trade_show',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Donald',
                'last_name' => 'Baker',
                'email' => 'donald.baker@energy.com',
                'phone' => '+44-20-7946-0968',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'partner',
                'status' => ContactStatus::DORMANT->value,
            ],
            [
                'first_name' => 'Helen',
                'last_name' => 'Gonzalez',
                'email' => 'helen.gonzalez@education.org',
                'phone' => '+1-555-0112',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'website',
                'status' => ContactStatus::NEW->value,
            ],
            [
                'first_name' => 'Paul',
                'last_name' => 'Nelson',
                'email' => 'paul.nelson@logistics.com',
                'phone' => '+81-3-1234-5683',
                'lead_level' => LeadLevel::CONTACT->value,
                'source' => 'referral',
                'status' => ContactStatus::ACTIVE->value,
            ],
            [
                'first_name' => 'Sandra',
                'last_name' => 'Carter',
                'email' => 'sandra.carter@consulting.com',
                'phone' => '+44-20-7946-0969',
                'lead_level' => LeadLevel::LEAD->value,
                'source' => 'other',
                'status' => ContactStatus::NEW->value,
            ],
        ];

        foreach ($contacts as $contactData) {
            Contact::create([
                'id' => \Ramsey\Uuid\Uuid::uuid7()->toString(),
                ...$contactData,
            ]);
        }
    }
}
