volumes:
  postgres-data:
  redis-data:

networks:
  frontend:
  backend:
name: "telemain"
services:
  proxy:
    container_name: telemain-proxy
    image: nginx:latest
    ports:
      - "127.0.0.1:8199:80"
    volumes:
      - ../backend:/var/www/app
      - ../.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend
    depends_on:
      - php

  php:
    container_name: telemain-php
    build:
      context: ..
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ../backend:/var/www/app
    networks:
      - backend
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: telemain-db
    image: postgres:latest
    ports:
      - "127.0.0.1:5419:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ../backend/.env
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'telemain-db'
      POSTGRES_USER: 'user'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - backend

  redis:
    container_name: telemain-redis
    image: redis:latest
    sysctls:
      - net.core.somaxconn=511
    volumes:
      - redis-data:/data
    networks:
      - backend
