FROM php:8.4-fpm

# Install system dependencies
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
    aptitude \
    build-essential \
    byobu \
    ca-certificates \
    cmake \
    cron \
    curl \
    ghostscript \
    git \
    htop \
    imagemagick \
    libaom-dev \
    libbz2-dev \
    libcurl4 \
    libcurl4-gnutls-dev \
    libfreetype6-dev \
    libheif-dev \
    libiconv-hook-dev \
    libicu-dev \
    libjpeg-dev \
    libjpeg62-turbo-dev \
    liblua5.3-0 \
    liblua5.3-dev \
    libmagickwand-dev \
    libmemcached-dev \
    libmemcached11 \
    libonig-dev \
    libpcre3 \
    libpcre3-dev \
    libpng-dev \
    libpq-dev \
    libssl-dev \
    libwebp-dev \
    libxml2 \
    libxml2-dev \
    libxslt-dev \
    libzip-dev \
    man \
    nano \
    nginx \
    openssl \
    software-properties-common \
    supervisor \
    unzip \
    wget \
    zlib1g-dev && \
    rm -rf /var/lib/apt/lists/* && \
# Configure and install PHP extensions
    docker-php-ext-configure zip && \
    docker-php-ext-configure intl && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install \
        bcmath \
        ctype \
        curl \
        dom \
        exif \
        fileinfo \
        gd \
        iconv \
        intl \
        mbstring \
        opcache \
        pdo \
        pdo_mysql \
        pdo_pgsql  \
        pgsql \
        simplexml \
        soap \
        sockets \
        xml \
        xsl \
        zip && \
    # Install PECL extensions and enable
    pecl install imagick redis && \
    docker-php-ext-enable imagick redis

# Copy Composer from official image
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Set up php.ini and CA certs
RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini" && \
    update-ca-certificates && \
# Install Node.js and npm
curl -sL https://deb.nodesource.com/setup_24.x | bash - && \
apt-get install -y nodejs && \
rm -rf /var/lib/apt/lists/*

# Add cron job for Laravel scheduler
RUN echo "* * * * * cd /var/www/app && /usr/local/bin/php artisan schedule:run >> /dev/null 2>&1" | crontab -

# Set working directory
WORKDIR /var/www/app

# Add php alias
RUN ln -s /usr/local/bin/php /usr/local/bin/php8.0

# Copy supervisord config
COPY .docker/php/supervisord.conf /etc/supervisor/supervisord.conf
COPY .docker/php/start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

EXPOSE 80

CMD ["/usr/local/bin/start.sh"]


